# Pytorch Tensor Tutorial

## Initializing a Tensor

In [1]:
import torch 

my_tensor = torch.tensor([[1,2,3],[4,5,6]]) 

my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

- float16: Lower precision, less memory, faster computation. Useful for reducing model size and increasing speed, especially on compatible hardware.
  
- float32: Standard precision, moderate memory usage, widely used in training and inference of deep learning models.
  
- float64: Higher precision, more memory, slower computation. Used when higher precision calculations are necessary.

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu" 

my_tensor = torch.tensor([[1,2,3],[4,5,6]], 
                        dtype = torch.float32,
                        device = device,
                        requires_grad= True)  
print(my_tensor)

print(f'dtype: {my_tensor.dtype}')
print(f'device: {my_tensor.device}')
print(f'shape: {my_tensor.shape}') 
print(f'requiers_grad: {my_tensor.requires_grad}')

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
dtype: torch.float32
device: cpu
shape: torch.Size([2, 3])
requiers_grad: True


## Some other common initialize 

A tensor was created by **torch.empty()** will contain random values from the allocated memory, not initialized according to any particular rule.

In [3]:
x = torch.empty(size = (2,3)) 
x

tensor([[-9.3016e-36,  3.2118e-41,  1.1224e-42],
        [ 0.0000e+00, -2.5633e-21,  4.1404e-41]])

In [4]:
x = torch.zeros((3,4)) 
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
x = torch.rand((3,4))
x

tensor([[0.6748, 0.4375, 0.7936, 0.9642],
        [0.7959, 0.8925, 0.6012, 0.8865],
        [0.0039, 0.6060, 0.5570, 0.4093]])

**torch.rand()**: Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)

In [6]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
x = torch.eye(5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

**torch.eye(n,m = None)** 

n: the number of rows (int)

m: the number of columns (int, optional, default = n )

In [8]:
x = torch.range(start=1,end=5,step=1)
x

/tmp/ipykernel_138969/2383827200.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.range(start=1,end=5,step=1)


tensor([1., 2., 3., 4., 5.])

In [9]:
x = torch.linspace(start=0.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

**torch.linspace()** creates a one-dimensional tensor of size **steps** whose values aer evenly spaced from **start** to **end** 

In [10]:
x = torch.empty(size = (3,3)).normal_(mean=0, std = 1)
x

tensor([[ 0.1220,  1.6240,  1.7994],
        [-0.1584, -0.0729,  0.3458],
        [ 1.3527,  0.7282, -0.2550]])

In [11]:
x = torch.empty((3,3)).uniform_(0,1)
x

tensor([[0.4886, 0.2384, 0.0747],
        [0.0805, 0.2022, 0.1582],
        [0.0878, 0.8717, 0.2791]])

In [12]:
x = torch.diag(torch.ones(5))
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
x = torch.diag(torch.range(start=1,end=5,step=1))
x

/tmp/ipykernel_138969/120779390.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.diag(torch.range(start=1,end=5,step=1))


tensor([[1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 0., 5.]])

## Initialize and convert tensors to the other types (init, float, double)


More information: [torch.dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype)

In [14]:
tensor = torch.range(0,5) 

# True or False
print(tensor.bool())

# dtype: int16
print(tensor.short()) 

# dtype: int64
print(tensor.long()) 

# dtype: float16
print(tensor.half()) 

# dtype: float32
print(tensor.float())

# dtype: float64
print(tensor.double())

tensor([False,  True,  True,  True,  True,  True])
tensor([0, 1, 2, 3, 4, 5], dtype=torch.int16)
tensor([0, 1, 2, 3, 4, 5])
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4., 5.])
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


/tmp/ipykernel_138969/1499690308.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor = torch.range(0,5)


## Array to Tensor Conversion

In [15]:
import torch 
import numpy 
  
# A numpy array of size 6 
a = numpy.array([1.0, -0.5, 3.4, -2.1, 0.0, -6.5]) 
print(a) 

t = torch.from_numpy(a) 
print(t) 

[ 1.  -0.5  3.4 -2.1  0.  -6.5]
tensor([ 1.0000, -0.5000,  3.4000, -2.1000,  0.0000, -6.5000],
       dtype=torch.float64)


In [16]:
import numpy as np 
import torch

np_array = np.ones((5,5)) 

tensor = torch.from_numpy(np_array) 

np_array_2 = tensor.numpy() 

In [17]:
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [18]:
np_array_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])