# Tensor Math & Comparison Operations

In [1]:
import torch 

x = torch.tensor([1,2,3,4,5])
y = torch.tensor([6,7,8,9,10]) 

## Tensor Math

### Addition

In [2]:
z1 = torch.add(x,y)
print(z1)

z2 = x + y
print(z2)

t = torch.ones(5)
t.add_(x)
print(t) 

t+=x
print(t) 

tensor([ 7,  9, 11, 13, 15])
tensor([ 7,  9, 11, 13, 15])
tensor([2., 3., 4., 5., 6.])
tensor([ 3.,  5.,  7.,  9., 11.])


### Subtraction

In [3]:
z1 = torch.subtract(x,y)
print(z1)

z2 = x - y 
print(z2)

tensor([-5, -5, -5, -5, -5])
tensor([-5, -5, -5, -5, -5])


### Division


In [4]:
z1 = torch.true_divide(x,y) 
print(z1)

z2 = x / y 
print(z2)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])
tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])


### Exponentiation

In [5]:
z1 = x.pow(2) 
print(z1)

z2 = x**2 
print(z2)

tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])


### Simple Comparison

In [6]:
x = torch.empty((3,5)).normal_(mean=0, std=1)
print(x)

tensor([[ 0.2337, -0.6817, -0.0712,  1.3727, -0.4706],
        [ 0.1839,  1.5235,  1.4722,  0.2069, -1.4236],
        [-0.2729, -0.9526, -1.6232,  0.2066, -0.2469]])


In [7]:
z = x > 0 
print(z)

tensor([[ True, False, False,  True, False],
        [ True,  True,  True,  True, False],
        [False, False, False,  True, False]])


In [8]:
z = x < 0 
print(z)

tensor([[False,  True,  True, False,  True],
        [False, False, False, False,  True],
        [ True,  True,  True, False,  True]])


### Matrix Mutiplication

In [9]:
x = torch.rand((3,5))
y = torch.rand((5,4))

z1 = torch.mm(x,y)
print(z1)

z2 = x.mm(y)
print(z2)

tensor([[1.4102, 1.1402, 1.0952, 0.6300],
        [2.0225, 1.1468, 1.2621, 1.2951],
        [1.4217, 1.1220, 1.1086, 0.7739]])
tensor([[1.4102, 1.1402, 1.0952, 0.6300],
        [2.0225, 1.1468, 1.2621, 1.2951],
        [1.4217, 1.1220, 1.1086, 0.7739]])


### Matrix Exponentiation

In [10]:
x = torch.rand(2,2)
print(f'x : {x}')
z1 = torch.matrix_power(x,3) 
print(z1)

z2 = x.matrix_power(3) 
print(z2)

x : tensor([[0.1053, 0.8678],
        [0.7400, 0.3304]])
tensor([[0.3485, 0.6918],
        [0.5900, 0.5280]])
tensor([[0.3485, 0.6918],
        [0.5900, 0.5280]])


### Dot Product

In [11]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

z1 = x*y 
print(z)

z2 = torch.dot(x,y) 
print(z2)

tensor([[False,  True,  True, False,  True],
        [False, False, False, False,  True],
        [ True,  True,  True, False,  True]])
tensor(46)


### Batch Matrix Multiplication

![imag](https://daehyun-bigbread.github.io/assets/img/20210710_163929.png)

In [12]:
batch = 2
n = 2
h = 4 
m = 3
tensor1 = torch.rand((batch, n, h)) 
print(f'tensor1:\n{tensor1}\n')

tensor2 = torch.rand((batch, h, m))
print(f'tensor2:\n{tensor2}') 

tensor1:
tensor([[[0.3728, 0.7677, 0.4233, 0.2599],
         [0.4207, 0.0590, 0.0362, 0.1542]],

        [[0.7629, 0.5782, 0.5238, 0.5190],
         [0.6679, 0.4429, 0.6481, 0.8073]]])

tensor2:
tensor([[[0.5024, 0.2090, 0.5946],
         [0.5139, 0.3778, 0.9885],
         [0.7976, 0.4918, 0.6921],
         [0.3705, 0.6124, 0.6036]],

        [[0.7014, 0.4816, 0.0905],
         [0.4460, 0.4545, 0.6032],
         [0.5475, 0.1456, 0.4522],
         [0.4501, 0.5105, 0.4077]]])


In [13]:
output_bmm = torch.bmm(tensor1, tensor2) # size: (batch, n, m) 
print(f'output:\n{output_bmm}')

output:
tensor([[[1.0157, 0.7352, 1.4303],
         [0.3277, 0.2224, 0.4266]],

        [[1.3134, 0.9714, 0.8663],
         [1.3843, 1.0294, 0.9498]]])


### Broadcasting

![image](https://blog.kakaocdn.net/dn/nkBPO/btrnJBEILeo/k3WxqqQsjtU8bQVjfvpSm0/img.png)

In [14]:
x = torch.randint(0, 5, size = (5,5))
print(x)

y = torch.randint(0,5, size = (1,5)) 
print(y)

z = x+y 
print(z)



tensor([[2, 4, 4, 2, 3],
        [3, 2, 3, 4, 3],
        [0, 0, 1, 3, 0],
        [1, 1, 4, 1, 3],
        [3, 2, 4, 1, 0]])
tensor([[1, 2, 4, 2, 0]])
tensor([[3, 6, 8, 4, 3],
        [4, 4, 7, 6, 3],
        [1, 2, 5, 5, 0],
        [2, 3, 8, 3, 3],
        [4, 4, 8, 3, 0]])


### Other useful tensor operations 

#### torch.sum

In [15]:
print(x)
sum_x = torch.sum(x, dim = 0)

print(sum_x)

tensor([[2, 4, 4, 2, 3],
        [3, 2, 3, 4, 3],
        [0, 0, 1, 3, 0],
        [1, 1, 4, 1, 3],
        [3, 2, 4, 1, 0]])
tensor([ 9,  9, 16, 11,  9])


#### torch.max

In [16]:
values, indices = torch.max(x, dim = 0)
print(f'Values: \t{values}\nIndices: \t{indices}')

Values: 	tensor([3, 4, 4, 4, 3])
Indices: 	tensor([1, 0, 0, 1, 0])


#### torch.min

In [17]:
values, indices = torch.min(x, dim = 1)
print(f'Values: \t{values}\nIndices: \t{indices}')

Values: 	tensor([2, 2, 0, 1, 0])
Indices: 	tensor([0, 1, 0, 0, 4])


#### torch.abs

In [18]:
n = torch.randint(-5, -1, size = (4,5))
print(n) 

abs_n = torch.abs(n) 
print(abs_n) 

tensor([[-3, -2, -5, -5, -5],
        [-4, -2, -4, -3, -3],
        [-5, -5, -2, -2, -5],
        [-2, -3, -3, -5, -5]])
tensor([[3, 2, 5, 5, 5],
        [4, 2, 4, 3, 3],
        [5, 5, 2, 2, 5],
        [2, 3, 3, 5, 5]])


#### torch.argmax

In [19]:
values, indices = torch.max(x, dim = 1)

print(x)

print(f'Values: \t{values}\nIndices: \t{indices}')

indices = torch.argmax(x, dim = 1)
print(indices)

tensor([[2, 4, 4, 2, 3],
        [3, 2, 3, 4, 3],
        [0, 0, 1, 3, 0],
        [1, 1, 4, 1, 3],
        [3, 2, 4, 1, 0]])
Values: 	tensor([4, 4, 3, 4, 4])
Indices: 	tensor([1, 3, 3, 2, 2])
tensor([1, 3, 3, 2, 2])


#### torch.argmin

In [20]:
values, indices = torch.min(x, dim = 1)

print(x)

print(f'Values: \t{values}\nIndices: \t{indices}')

indices = torch.argmin(x, dim = 1)
print(indices)

tensor([[2, 4, 4, 2, 3],
        [3, 2, 3, 4, 3],
        [0, 0, 1, 3, 0],
        [1, 1, 4, 1, 3],
        [3, 2, 4, 1, 0]])
Values: 	tensor([2, 2, 0, 1, 0])
Indices: 	tensor([0, 1, 0, 0, 4])
tensor([0, 1, 0, 0, 4])


#### torch.mean

In [21]:
print(x) 

z1 = torch.mean(x.float(), dim = 1) 
print(z1)

z2 = torch.mean(x.float(), dim = 0) 
print(z2)

z = torch.mean(x.float())
print(z)


tensor([[2, 4, 4, 2, 3],
        [3, 2, 3, 4, 3],
        [0, 0, 1, 3, 0],
        [1, 1, 4, 1, 3],
        [3, 2, 4, 1, 0]])
tensor([3.0000, 3.0000, 0.8000, 2.0000, 2.0000])
tensor([1.8000, 1.8000, 3.2000, 2.2000, 1.8000])
tensor(2.1600)


#### torch.eq


In [22]:
print(f'x:\n{x}')

print(f'y:\n{y}')

z = torch.eq(x,y) 
print(f'z:\n{z}')

x:
tensor([[2, 4, 4, 2, 3],
        [3, 2, 3, 4, 3],
        [0, 0, 1, 3, 0],
        [1, 1, 4, 1, 3],
        [3, 2, 4, 1, 0]])
y:
tensor([[1, 2, 4, 2, 0]])
z:
tensor([[False, False,  True,  True, False],
        [False,  True, False, False, False],
        [False, False, False, False,  True],
        [ True, False,  True, False, False],
        [False,  True,  True, False,  True]])


#### torch.sort

In [23]:
print(x) 

z = torch.sort(x, dim = 1, descending= False )

print(z)

tensor([[2, 4, 4, 2, 3],
        [3, 2, 3, 4, 3],
        [0, 0, 1, 3, 0],
        [1, 1, 4, 1, 3],
        [3, 2, 4, 1, 0]])
torch.return_types.sort(
values=tensor([[2, 2, 3, 4, 4],
        [2, 3, 3, 3, 4],
        [0, 0, 0, 1, 3],
        [1, 1, 1, 3, 4],
        [0, 1, 2, 3, 4]]),
indices=tensor([[0, 3, 4, 1, 2],
        [1, 0, 2, 4, 3],
        [0, 1, 4, 2, 3],
        [0, 1, 3, 4, 2],
        [4, 3, 1, 0, 2]]))


#### torch.clamp


In [24]:
tensor = torch.randint(-20, 20, (5,5))
print(tensor)

z = torch.clamp(tensor, min = 0 , max= 10)
print(z)

tensor([[ -6, -20,   3, -18, -14],
        [ 15,  14,  -8,  -1,  -4],
        [  0,  -3, -10, -13,   0],
        [ -1, -17,  15,  10,   7],
        [-14, -16,  -8,  15,  14]])
tensor([[ 0,  0,  3,  0,  0],
        [10, 10,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0, 10, 10,  7],
        [ 0,  0,  0, 10, 10]])


#### torch.any, torch.all

In [25]:
tensor = torch.tensor([0,0,1,0,1])

z = tensor.bool()

print(z)

tensor([False, False,  True, False,  True])
