# Tensor Indexing


In [1]:
import torch

batch_size = 5 
features = 25

x = torch.rand((batch_size, features))
print(x)

tensor([[0.3640, 0.9714, 0.5341, 0.2975, 0.9719, 0.7664, 0.7090, 0.9671, 0.7837,
         0.9968, 0.2605, 0.2647, 0.6565, 0.4012, 0.4407, 0.3523, 0.6592, 0.7083,
         0.2393, 0.0362, 0.8398, 0.6352, 0.1299, 0.0459, 0.9769],
        [0.5510, 0.9434, 0.6035, 0.0989, 0.3161, 0.0744, 0.9634, 0.2633, 0.9175,
         0.1918, 0.3117, 0.7399, 0.4426, 0.1532, 0.7727, 0.9278, 0.8141, 0.7861,
         0.3026, 0.2797, 0.4657, 0.1576, 0.9406, 0.0992, 0.5856],
        [0.4885, 0.4096, 0.8937, 0.0742, 0.3109, 0.5160, 0.1180, 0.1161, 0.4458,
         0.2787, 0.6093, 0.8043, 0.8742, 0.2788, 0.7195, 0.0012, 0.9033, 0.8535,
         0.0180, 0.7715, 0.3043, 0.1207, 0.5039, 0.8900, 0.4638],
        [0.3791, 0.5608, 0.8670, 0.9427, 0.6668, 0.7769, 0.8197, 0.8410, 0.7563,
         0.3996, 0.5451, 0.5785, 0.7426, 0.6027, 0.7956, 0.1680, 0.2913, 0.8746,
         0.2908, 0.5109, 0.7907, 0.4241, 0.7117, 0.3228, 0.5159],
        [0.3549, 0.4031, 0.1186, 0.2015, 0.8282, 0.7621, 0.4407, 0.7564, 0.3597,
       

In [2]:
print(x[1,:])
print(x[1,:].shape) 

tensor([0.5510, 0.9434, 0.6035, 0.0989, 0.3161, 0.0744, 0.9634, 0.2633, 0.9175,
        0.1918, 0.3117, 0.7399, 0.4426, 0.1532, 0.7727, 0.9278, 0.8141, 0.7861,
        0.3026, 0.2797, 0.4657, 0.1576, 0.9406, 0.0992, 0.5856])
torch.Size([25])


In [3]:
print(x[2:4,0:10])
print(x[2:4,0:10].shape)

tensor([[0.4885, 0.4096, 0.8937, 0.0742, 0.3109, 0.5160, 0.1180, 0.1161, 0.4458,
         0.2787],
        [0.3791, 0.5608, 0.8670, 0.9427, 0.6668, 0.7769, 0.8197, 0.8410, 0.7563,
         0.3996]])
torch.Size([2, 10])


In [4]:
print(x[1:3,4])

tensor([0.3161, 0.3109])


In [5]:
y =torch.arange(start=10, end=20, step=1)
print(y)

indices = [1,3,5]
print(y[indices])

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([11, 13, 15])


In [6]:
x = torch.rand((5,5)) 
print(x)

rows = torch.tensor([1,3])
cols = torch.tensor([0,2])

print(x[rows, cols]) 

tensor([[0.3709, 0.0356, 0.6932, 0.0465, 0.7628],
        [0.3203, 0.4637, 0.3897, 0.5716, 0.8017],
        [0.0269, 0.0962, 0.0632, 0.9161, 0.6288],
        [0.5999, 0.6520, 0.2562, 0.1116, 0.9861],
        [0.9958, 0.3612, 0.6936, 0.4858, 0.8609]])
tensor([0.3203, 0.2562])


In [7]:
x = torch.arange(10) 
print(x)

x[(x < 2) | ( x > 8)] 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([0, 1, 9])

In [8]:
x[x.remainder(3) == 0] 

tensor([0, 3, 6, 9])

#### torch.where

In [9]:
x = torch.where(x<=5,x, x*10) 
print(x)

tensor([ 0,  1,  2,  3,  4,  5, 60, 70, 80, 90])


#### unique()

In [10]:
x = torch.tensor([0,0,1,1,1,2,2,3,4])

y = x.unique() 
y

tensor([0, 1, 2, 3, 4])

#### ndimension() 

In [11]:
x = torch.tensor([0,0,1,1,1,2,2,3,4])

vector = torch.rand((4,5))

tensor = torch.rand((5,5,5)) 

print(x.ndimension())
print(vector.ndimension()) 
print(tensor.ndimension()) 

1
2
3


#### numel() 

Returns the total number of elements in the input tensor

In [12]:
x.numel() 

9

In [13]:
vector.numel()

20

In [14]:
tensor.numel() 

125