# Tensor Reshaping Dimensions 

**view()**: Returns a new tensor with the same data as the self tensor but of a different shape.

In [1]:
import torch

x = torch.rand(9) 
print(x) 

x_3x3 = x.view(3,3) 

print(x_3x3)

x_3x3 = x.reshape(3,3)

tensor([0.6790, 0.9522, 0.3843, 0.8534, 0.6194, 0.9979, 0.8282, 0.4112, 0.2705])
tensor([[0.6790, 0.9522, 0.3843],
        [0.8534, 0.6194, 0.9979],
        [0.8282, 0.4112, 0.2705]])


In [2]:
y = x_3x3.t()  # transpose 
y

tensor([[0.6790, 0.8534, 0.8282],
        [0.9522, 0.6194, 0.4112],
        [0.3843, 0.9979, 0.2705]])

In [3]:
y.contiguous().view(9) 

tensor([0.6790, 0.8534, 0.8282, 0.9522, 0.6194, 0.4112, 0.3843, 0.9979, 0.2705])

#### cat()

In [4]:
x = torch.rand((2,5))
y = torch.rand((2,5))

z1 = torch.cat((x,y), dim = 0 )
print(z1.shape)

z2 = torch.cat((x,y), dim = 1)
print(z2.shape)


torch.Size([4, 5])
torch.Size([2, 10])


In [5]:
z = x.view(-1)
z

tensor([0.1343, 0.9081, 0.1240, 0.3300, 0.5535, 0.5440, 0.4547, 0.7685, 0.2145,
        0.1363])

In [18]:
tensor = torch.rand(2,10,10)
tensor.size(0)

2

In [6]:
batch = 64 

x = torch.rand((batch,2,5))
x.view(-1).shape

torch.Size([640])

#### torch.permute


Returns a view of the original tensor input with its dimensions permuted.

In [7]:
x = torch.randn(2, 3, 5)
print(x)
print(x.shape) 

y = torch.permute(x, (2, 0, 1))
print(y)
print(y.shape) 

tensor([[[ 0.3821,  1.6129,  0.3420,  0.8177,  1.1629],
         [-0.8030,  0.5712,  1.5485,  1.7602,  0.0241],
         [-0.1950, -0.6898,  0.1702,  2.2470, -0.2538]],

        [[ 0.3064, -0.7119, -0.1609,  0.0709, -1.4795],
         [-0.6361, -0.0513, -0.6911, -1.5155, -1.3226],
         [ 0.5488,  0.5819,  0.1603, -1.6707, -0.4839]]])
torch.Size([2, 3, 5])
tensor([[[ 0.3821, -0.8030, -0.1950],
         [ 0.3064, -0.6361,  0.5488]],

        [[ 1.6129,  0.5712, -0.6898],
         [-0.7119, -0.0513,  0.5819]],

        [[ 0.3420,  1.5485,  0.1702],
         [-0.1609, -0.6911,  0.1603]],

        [[ 0.8177,  1.7602,  2.2470],
         [ 0.0709, -1.5155, -1.6707]],

        [[ 1.1629,  0.0241, -0.2538],
         [-1.4795, -1.3226, -0.4839]]])
torch.Size([5, 2, 3])


#### unsqueeze

In [8]:
x = torch.arange(10)
print(x) 
print(x.unsqueeze(0)) 
print(x.unsqueeze(1))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [9]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(z.shape)

torch.Size([10])


#### squeeze

In [10]:
print(x)
z = x.squeeze(1) 
z

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])


tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])